"""change type of added_at in Film table

Revision ID: 206ba596ed52
Revises: 303db8111c2a
Create Date: 2026-01-19 13:34:42.603450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206ba596ed52'
down_revision: Union[str, Sequence[str], None] = '303db8111c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE film
            ALTER COLUMN added_at
            TYPE TIMESTAMP WITHOUT TIME ZONE
            USING to_timestamp(added_at)
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE film
            ALTER COLUMN added_at
            TYPE INTEGER
            USING EXTRACT(EPOCH FROM added_at)::INTEGER
        """)
    # ### end Alembic commands ###
