"""fixed last_login,created_at  columns in user table

Revision ID: 303db8111c2a
Revises: b37fb088238a
Create Date: 2026-01-14 20:32:23.502367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303db8111c2a'
down_revision: Union[str, Sequence[str], None] = 'b37fb088238a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
