"""added token column in user table

Revision ID: 508d0c3fe0d5
Revises: d579dc7357e2
Create Date: 2026-01-14 19:06:53.289405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508d0c3fe0d5'
down_revision: Union[str, Sequence[str], None] = 'd579dc7357e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['country_name'])
    op.create_unique_constraint(None, 'genre', ['genre'])
    op.add_column('user', sa.Column('token', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'token')
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
