"""added last_login and created_at

Revision ID: c378b5a4bb96
Revises: 677c51c7e780
Create Date: 2025-12-24 14:59:17.217812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c378b5a4bb96'
down_revision: Union[str, Sequence[str], None] = '677c51c7e780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
